# list of words that are generally bad by themselves or within words
bad_word_segments:
 
# list of words that are generally only bad by themselves
bad_word_singles:

# when replacing with characters, leave the first letter to hint at what was replaced?
leave_first_character: true

# when true, replacement characters are shuffled each use
shuffle_replacement_characters: false

# string of characters to use for replacement, will be shuffled if the above option is true
replacement_characters: "@#$%!?*&"