###########################################################################################
#
#  DEV ENVIRONMENT VARIABLES
#
###########################################################################################

# Just an example use case
# enable_analytics: no