# when set to `true`, HTML caching will be enabled
enable: false

# how long should pages be cached for? set this to either:
#   - a time value, like "10 minutes"
#   - "on cache update", which will invalidate the cache whenever any piece of content is touched
#   - "on last modified", which will invalidate the cache based on that URL's content file's last-modified time
cache_length: on last modified

# a pipe-separated list of URLs you want to exclude from HTML caching, ending-wildcards OK
exclude: 

# when `true`, different query strings in URLs will all result in the same page being shown,
# for example /about and /about?something will all show the same page: /about
# this prevents people from appending "?whatever" to URLs to force the page to re-cache, but
# will break any pages relying on query strings, like pages with pagination
ignore_query_strings: false