#####################################
#
#  English (by Statamic)
#
# ###################################

translations:

  # Universal
  add: Add
  delete: Delete
  list: List
  none: None
  view: View
  in: in
  remove: Remove
  cancel: Cancel
  move: Move
  toggle: Toggle
  
  # Timing
  today: Toissday
  tomorrow: Tomorrow
  yesterday: Yesterday
  at: at

  # Nav
  home: Home
  dashboard: Dashboard
  pages: Pages
  content: Content
  members: Members
  account: Account
  system: System
  help: Help
  view_site: View Site
  logout: Log out
  logs: Logs

  # Entries
  entry: Entry
  entries: Entries
  create: Create
  new_entry: New Entry
  editing_entry: Editing entry
  create_entry: Create Entry
  delete_entry: Delete Entry
  view_entry: View Entry
  list_entries: List Entries
  take_action: Take Action
  delete_entries: Delete Entries
  confirm_delete: Yes I'm Sure
  confirm_action: Yes I'm Sure

  # Pages
  page: Page
  edit_page: Edit Page
  editing_page: Editing Page
  new_top_level_page: New Top Level Page
  site_pages: Site Pages
  new_child_page: New Child Page
  view_page: View Page
  delete_page: Delete Page
  select_new_page_type: Select New Page Type
  parent: Parent
  or: or
  and: and
  pagedelete_confirm: "Are you sure you wish to delete this page?"

  update_available: update available
  up_to_date: up to date
  offline: The control panel is currently offline.

  # Publish
  title: Title
  slug: Slug
  date: Date
  number: Number
  editing: Editing
  enter_title: Enter a title...
  order_number: Order Number
  publish_date: Publish Date
  publish_time: Publish Time
  save: Save
  save_publish: "Publish"
  save_publish_continue: "Publish & Continue"
  content: Content
  new: New

  # Statuses
  status: Status
  live: Live
  draft: Draft
  hidden: Hidden

  # Members and forms
  login: Log in
  admin: Admin
  email: Email
  username: Username
  password: Password
  password_confirmation: Password Confirmation
  change_password: Change Password
  type_again: "Type it again, please"
  encrypt_password: Encrypt Password?
  first_name: First Name
  last_name: Last Name
  biography: Biography
  role: Role
  member: Member
  new_member: New Member
  creating_member: Creating new member
  editing_member: "Editing member: "
  reset_password_url_invalid: This URL is invalid
  reset_password_url_expired: This link has expired
  member_doesnt_exist: Member doesn't exist

  # Logs
  site_logs: Site Logs
  clear_logs: Clear all logs
  log_file: Your log file
  log_unwritable: is not writable, and thus, logs cannot be written.
  showing: Showing
  messages_all: all messages
  messages_debug: only debug messages
  messages_info: only info messages
  messages_warn: only warn messages
  messages_error: only error messages
  messages_fatal: only fatal messages
  info_plus: info messages or worse
  warn_plus: warn messages or worse
  error_plus: error messages or worse
  messages_happened: that happened on
  messages_level: Level
  messages_when: When
  messages_what: What Caused This
  messages_page: Page
  messages_message: Message
  log_filter_nomessages: "This log file exists, but contains no messages with this filter."
  log_nomessages: "This log file exists, but there are no messages."
  log_nomessages_logged: "No messages have been logged yet."
  logging_yes: "This site <strong>is</strong> logging messages."
  logging_no: "This site <strong>is not</strong> logging messages."
  log_messages: "Messages are from the following level or worse: "
  log_turning_on: "To turn on logging, set <code>_log_enabled</code> to <code>true</code> in <code>_config/settings.yaml</code>."

  # Static Site Generator
  export_to_html: Export to HTML
  static_site_generator: Static Site Generator
  generated_files: Generated Files
  generate_html: Generate HTML Files
  download_site: Download Site

  # Messages, Errors & Confirmations
  site_unlicensed: This site is unlicensed. Please purchase and enter your license key.
  admin_404: "That page did not exist, so we sent you here instead."
  already_exists: already exists
  is_required: is required
  content_not_found: "Content not found!"
  content_not_writable: "Whoops, your content folder and/or files aren't writable. You'll want to fix that."
  users_not_writable: "Whoops, your users folder and/or files aren't writable. You'll want to fix that."
  msg_password_encrypted: "Password has been encrypted. Please login again."
  password_confirmation_required: "and confirmation is required"
  password_confirmation_match: "and confirmation do not match"
  password_confirmation_does_not_match: "Password and password confirmation do not match."
  incorrect_username: Username not found
  incorrect_password: Incorrect password
  incorrect_username_password: "Incorrect username or password. Try again."
  entry_deleted: "Entry successfully deleted!"
  entries_deleted: "Entries successfully deleted!"
  page_deleted: "Page successfully deleted!"
  page_unable_delete: "Unable to delete page."
  member_deleted: "Member successfully deleted!"
  page_saved: "Page saved successfully!"
  entry_saved: "Entry saved successfully!"
  member_saved: "Member saved successfully!"
  invalid_username: "The username entered contains invalid characters."
  username_already_exists: "Someone with that username already exists."
  viewing_all: Viewing all

  error: Error
  error_form_submission: "Sorry, an error prevented the form submission."
  are_you_sure: Are you sure? This cannot be undone.
  access_denied: Access Denied
  enable_curl: cURL must be enabled to perform a security test.
  
  # File-upload errors
  upload_error_ini_size: File upload failed. The file’s size is more than PHP’s configuration allows.
  upload_error_form_size: File upload failed. The file’s size is more than the `MAX_FILE_SIZE` on the form allows.
  upload_error_err_partial: File upload failed. The file was only partially uploaded.
  upload_error_no_file: File upload failed. No file was chosen for upload.
  upload_error_no_temp_dir: File upload failed. No temporary directory has been specified.
  upload_error_cant_write: File upload failed. The temporary upload directory may not be writable.
  upload_error_extension: File upload failed. A PHP extension has stopped the file upload from working.
  upload_error_unknown: File upload failed for unknown reasons.

  # Security
  security_status: Security Status
  security_files_security_check: Site Files Security Check
  secure_status: Secure Status
  password_status: Password Status
  curl_needed: "You'll need to enable cURL on your server to automatically test your security."
  folder_file: Folder/File
  action_required: Action Required
  secure: Secure
  unsecure: Unsecure
  user_accounts_security_check: User Accounts Security Check
  user_file: User File
  encrypted: Encrypted
  unencrypted: Unencrypted
  action_encrypt_password: Encrypt Password
  security_app_folder: "Your application folder is accessible to the web. While not critical, it's best practice to protect this folder."
  security_config_folder: "Your config folder is accessible to the web. It is critical that you protect this folder."
  security_settings_files: "Your settings files are accessible to the web. It is critical that you protect these files."
  security_user_files: "Your user files are accessible to the web. It is critical that you protect these files."
  security_content_folder: "Your content folder is accessible to the web. While not critical, it is best practice to protect this folder."
  security_template_files: "Your theme template files are accessible to the web. While not critical, it is best practice to protect these files."
  security_logs_folder: "Your logs folder is accessible to the web. It is critical that you protect this folder."

  # Location
  location_name: Name of Location
  latitude: Latitude
  longitude: Longitude

  # Raven
  export_csv: Export to CSV
  raven: Raven
  raven_forms: Raven Forms
  form: Form
  submissions: Submissions

  # Revisions
  view_page_history: View Page History
  choose_revision_to_view: Choose a revision to view
  view_this_revision: View this revision
  first_save: First saved revision
  published_on: Published on
  you_are_here: You Are Here
  viewing_revision: You are viewing a revision of this page from %s. You can re-publish it as-is, make changes then publish, or
  viewing_revision_link: go back to the live version
  what_changed: Describe What Changed
  file_deleted: File deleted
  file_renamed: File renamed
  
  # File
  upload_file: Upload a file
  drop_your_file: Drop your file
  max_files_reached: Max files reached
  choose_existing_file: Choose an existing file
  choose_file_from: Choose a file from
  file_deleted: File deleted
  file_doesnt_exist: File does not exist
  file_no_config: No config provided
  file_no_path: No path provided
  file_deleting_not_permitted: Deleting files is not permitted

  # Replicator
  hide_all: Hide all
  show_all: Show all
