_license_key:
_language: en
_site_name: Another Awesome Statamic Site
_content_root: _content
_site_url: http://statamic.com
_theme: acadia
_entry_timestamps: false
_date_format: 'F jS, Y'
_time_format: 'g:i.s a'
_timezone: America/New_York
_taxonomy:
  - categories
  - tags
_taxonomy_slugify: false
_taxonomy_case_sensitive: false
_taxonomy_force_lowercase: true
_content_type: markdown
_enable_smartypants: true
_theme_cache_bust: false
_transform_destination: assets/img/resized
_allow_php: false
_yaml_mode: loose
_markdown_parser: standard
_parse_order:
  - content
  - tags
_fix_out_of_range_pagination: true
_http_cache_expires: false
_disable_member_cache: false
_environments:
  dev:
    - 'http://localhost*'
    - '*.dev'
    - '*.localip'
  live:
    - '*.com'
_log_enabled: false
_log_level: debug
_log_file_path: _logs
_log_file_prefix: site
_display_debug_panel: true

_admin_enabled: true
_admin_path: admin
_admin_theme: ascent
_admin_nav:
  dashboard: false
  pages:     true
  members:   true
  account:   true
  system:    true
  logs:      true
  help:      true
  view_site: true
  logout:    true
_admin_start_page: pages
_enable_add_top_level_page: true
_enable_add_child_page: true
_enable_delete_page: true
_prepend_site_root_to_uploads: false
_allow_file_field_deletions: false
_disable_google_fonts: false
_cookies.lifetime: 1 day
_cookies.cipher: MCRYPT_RIJNDAEL_256
_cookies.cipher_mode: MCRYPT_MODE_CBC
_custom_transliteration:
_mode: 0755
_public_path: