#########################################################################
#
# REDACTOR FIELDTYPE SETTINGS
#
# For a list of all options visit: http://imperavi.com/redactor/docs/settings/
#
#########################################################################

# Automatically resize to show all written content
autoresize: true

# Order and choose your buttons. Use '|' for a vertical seperator
buttons:
  - formatting
  - bold
  - italic
  - deleted
  - unorderedlist
  - orderedlist
  - outdent
  - indent
  - image
  - file
  - video
  - table
  - link
  - horizontalrule
  - fontcolor
  - backcolor
  - alignleft
  - aligncenter
  - alignright
  - justify
  - html
  
# Turn on/off cleanup on paste
cleanup: true

# Automatically replace divs with paragraphs
convertDivs: true

# Automatically turn image links into <img> tags
convertImageLinks: false

# Automatically replace URLs with hyperlinks
convertLinks: true

# Automatically embed YouTube and Vimeo links
convertVideoLinks: false

# Turn on email tab in link modal window
linkEmail: true

# Set a default margin around images
imageFloatMargin: 10px

# Set the formatting tags available
formattingTags:
  - p
  - blockquote
  - pre
  - h1
  - h2
  - h3
  - h4

# Set a minimum height (in pixels)
minHeight: 150

# Turn on/off paragraph formatting
paragraphy: true

# Turn on/off keypress shortcuts
shortcuts: true

# Turn on/off the HTML source button on the toolbar
buttonSource: true